name: ðŸž Bug report
description: File a bug report for this sample application.
title: "[BUG] "
labels: ["bug"]
assignees:
  - seesharprun
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this bug report form so we can resolve your request.

        > [!TIP]
        > Providing additional context and repo steps helps us resolve your issue quickly.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Repro steps
      description: Provide steps to reproduce the bug in numbered format.
      value: |        
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Provide an explanation of the behavior you expected.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment, if possible.
      render: shell
    validations:
      required: false

