name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  continuous-integration-dotnet:
    name: .NET build and validation
    runs-on: ubuntu-latest
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        ports:
          - 8081:8081
          - 1234:1234
          - 10250-10255:10250-10255
        env:
          PROTOCOL: https
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x
            10.x
      - name: Validates code style and format
        working-directory: ./src
        run: |
          dotnet format --verify-no-changes --severity info
      - name: Build entire solution
        working-directory: ./src
        run: |
          dotnet build --configuration release
      - name: Validate package creation
        working-directory: ./src/tool
        run: |
          dotnet pack --configuration release
      - name: Run all unit tests
        working-directory: ./src
        run: |
          dotnet test --logger "trx;logfilename=xunit.trx"
      - name: Generate CTRF test results
        working-directory: ./src/tests
        run: |
          dotnet new tool-manifest
          dotnet tool install --local DotnetCtrfJsonReporter
          dotnet tool run DotnetCtrfJsonReporter --test-tool "xunit" --trx-path "integration/data/TestResults/xunit.trx" --output-directory "ctrf" --output-filename "report-integration-data.json"
          dotnet tool run DotnetCtrfJsonReporter --test-tool "xunit" --trx-path "unit/data/TestResults/xunit.trx" --output-directory "ctrf" --output-filename "report-unit-data.json"
      - name: Publish CTRF test results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './src/tests/ctrf/report-*-*.json'
        
        