name: Publish to NuGet
on: 
  workflow_dispatch:
    inputs:
      versionPrefix:
        description: 'Version prefix for the NuGet package'
        required: true
        default: '2.0.0'
      versionSuffix:
        description: 'Version suffix for the NuGet package'
        required: false
jobs:
  push-to-nuget:
    name: Push to NuGet
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Package NuGet stable models
        if: ${{ inputs.versionSuffix == '' }}
        run: dotnet pack CosmicWorks.Models/CosmicWorks.Models.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}"
      - name: Package NuGet preview models
        if: ${{ inputs.versionSuffix != '' }}
        run: dotnet pack CosmicWorks.Models/CosmicWorks.Models.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}" /p:VersionSuffix="${{ inputs.versionSuffix }}"
      - name: Package NuGet stable library
        if: ${{ inputs.versionSuffix == '' }}
        run: dotnet pack CosmicWorks.Data/CosmicWorks.Data.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}"
      - name: Package NuGet preview library
        if: ${{ inputs.versionSuffix != '' }}
        run: dotnet pack CosmicWorks.Data/CosmicWorks.Data.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}" /p:VersionSuffix="${{ inputs.versionSuffix }}"
      - name: Package NuGet stable generator
        if: ${{ inputs.versionSuffix == '' }}
        run: dotnet pack CosmicWorks.Generator/CosmicWorks.Generator.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}"
      - name: Package NuGet preview generator
        if: ${{ inputs.versionSuffix != '' }}
        run: dotnet pack CosmicWorks.Generator/CosmicWorks.Generator.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}" /p:VersionSuffix="${{ inputs.versionSuffix }}"
      - name: Package NuGet stable tool
        if: ${{ inputs.versionSuffix == '' }}
        run: dotnet pack CosmicWorks.Tool/CosmicWorks.Tool.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}"
      - name: Package NuGet preview tool
        if: ${{ inputs.versionSuffix != '' }}
        run: dotnet pack CosmicWorks.Tool/CosmicWorks.Tool.csproj --output out/ --include-symbols /p:VersionPrefix="${{ inputs.versionPrefix }}" /p:VersionSuffix="${{ inputs.versionSuffix }}"
      - name: Push NuGet packages
        working-directory: ./src/out
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
