name: Validate .NET code samples
on: pull_request 
jobs:
  validate-dotnet:
    name: Validate .NET project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Check .NET version
        run: dotnet --version
      - name: Build .NET project
        run: dotnet build CosmicWorks.sln
      - name: Check .NET code format
        run: dotnet format CosmicWorks.sln --verify-no-changes
